[Yayo's Animation] - Error rendering pawn portrait: Object reference not set to an instance of an object
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
(wrapper dynamic-method) yayoAni.Patch_PawnRenderer_RenderCache:yayoAni.Patch_PawnRenderer_RenderCache.Prefix_Patch0 (Verse.PawnRenderer,Verse.Pawn,System.Collections.Generic.Dictionary`2<RimWorld.Apparel, System.ValueTuple`2<UnityEngine.Color, bool>>,Verse.Rot4,single&,UnityEngine.Vector3,bool,bool,bool,bool,bool,System.Collections.Generic.Dictionary`2<RimWorld.Apparel, UnityEngine.Color>,System.Nullable`1<UnityEngine.Color>,bool)
(wrapper dynamic-method) Verse.PawnRenderer:Verse.PawnRenderer.RenderCache_Patch1 (Verse.PawnRenderer,Verse.Rot4,single,UnityEngine.Vector3,bool,bool,bool,bool,bool,System.Collections.Generic.IReadOnlyDictionary`2<RimWorld.Apparel, UnityEngine.Color>,System.Nullable`1<UnityEngine.Color>,bool)
RimWorld.PawnCacheRenderer:OnPostRender ()
(wrapper dynamic-method) RimWorld.PawnCacheRenderer:RimWorld.PawnCacheRenderer.RenderPawn_Patch1 (RimWorld.PawnCacheRenderer,Verse.Pawn,UnityEngine.RenderTexture,UnityEngine.Vector3,single,single,Verse.Rot4,bool,bool,bool,bool,bool,UnityEngine.Vector3,System.Collections.Generic.IReadOnlyDictionary`2<RimWorld.Apparel, UnityEngine.Color>,System.Nullable`1<UnityEngine.Color>,bool)
Verse.PawnRenderer:GetBlitMeshUpdatedFrame (Verse.PawnTextureAtlasFrameSet,Verse.Rot4,Verse.PawnDrawMode)
yayoAni.Yayo:GetBlitMeshUpdatedFrame (Verse.PawnTextureAtlasFrameSet,Verse.Rot4,Verse.PawnDrawMode,Verse.Pawn)
(wrapper dynamic-method) Verse.PawnRenderer:Verse.PawnRenderer.RenderPawnAt_Patch5 (Verse.PawnRenderer,UnityEngine.Vector3,System.Nullable`1<Verse.Rot4>,bool)
Verse.Pawn_DrawTracker:DrawAt (UnityEngine.Vector3)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.DrawAt_Patch1 (Verse.Pawn,UnityEngine.Vector3,bool)
Verse.Thing:Draw ()
Verse.ThingWithComps:Draw ()
(wrapper dynamic-method) Verse.DynamicDrawManager:Verse.DynamicDrawManager.DrawDynamicThings_Patch2 (Verse.DynamicDrawManager)
(wrapper dynamic-method) Verse.Map:Verse.Map.MapUpdate_Patch3 (Verse.Map)
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
